### ISSUE TITLE
Team 13 - Register user accepts invalid characters

### ISSUE THREAD

**Issue by joshuahaertel** [thyer/CS340winter2016#115]
Using characters not in the English alphabet breaks the server, i.e. username is José

**Comment by thyer** [comment]
This is an awesome bug

**Comment by joshuahaertel** [comment]
@thyer I thought a TA had originally reported this as P5 (we had not been added to the guthub yet so we could not label it ourselves) but when I enter with this name I cannot create a game. When I exit the client and log in as someone else I am not taken to any model and have free rain on the buttons.

Screenshot:
![screen shot 2016-03-03 at 10 24 41 am](https://cloud.githubusercontent.com/assets/16691565/13502910/2e979962-e12a-11e5-91d7-efa6d4d44dad.png)

As it appears it completely stops gameplay, should this be increased to a P2?

**Comment by menyx02** [comment]
I thought the deadline for logging bugs was yesterday

**Comment by mcrowder65** [comment]
Could you point me to the place in the project specs where we're supposed to handle non-english characters?

**Comment by thyer** [comment]
The added implication detail is valid since the issue was logged yesterday. And I've spoken with Team 13 and commented that this issue will need to be turned over to Bentz since he has final say over Dr. Snell's grades for this phase. 

That being said, I agree that this issue has the characteristics of a P2 bug. It's incorrect behavior and halts the game, rendering it unplayable. But P2 bugs are worth a sizeable point deficit and this kind of edge case is pretty extreme. @joshuahaertel has done a great job detecting and reporting it. I'll allow Bentz to determine the priority elevation, plus how points will be determined. 

@joshuahaertel, once again, kudos to you for finding this. And I'm a little disappointed not more people tried it once you reported it.
