### ISSUE TITLE
Inaccurate number of cities in resource bar 

### ISSUE THREAD

**Issue by emeraldarcher** [thyer/CS340winter2016#197]
Building a city doesn't decrease the number of cities the player has.

**Comment by thyer** [comment]
@mountain01 Mind tagging the duplicate issue?

**Comment by mountain01** [comment]
@thyer This issue is linked with #100. As I read the description for it, I guess I split it into two parts and this is a duplicate of the second part, only with cities instead of settlements. The functionality is so closely related that I marked this as a duplicate. If you fee like that shouldn't be the case then we can un mark this one.

**Comment by thyer** [comment]
Closing this as duplicate
