### ISSUE TITLE
Can create game with empty title

### ISSUE THREAD

**Issue by byurfl** [thyer/CS340winter2016#319]
A game with an empty title should not be allowed.

Steps to reproduce:
1. Log in.
2. Click "create game", leave the title field blank, and click "create game" button.

**Comment by jakebrucebrewer** [comment]
@thyer  Is this a bug?  @jvansteeter

**Comment by thyer** [comment]
The specifications state that the name cannot be null, but a cursory knowledge of Java tells us that the empty string is not null. That being said, I'd still like you to fix this since it can cause problems later and it's a super easy fix (five lines, max). Marking as a P5 so you won't lose any points for fixing it.

**Comment by jakebrucebrewer** [comment]
thanks @thyer
