### ISSUE TITLE
Some game elements wrong or missing when rejoining finished game

### ISSUE THREAD

**Issue by panzertime** [thyer/CS340winter2016#364]
Reproduce:
- Finish a game and return to the game lobby
- Rejoin the finished game
Expected behavior:
Game is as you left it
Actual behavior:
Main color bar across the top is missing, turn-tracker at bottom left shows incorrect scores

I'm not sure but it's possible this happens during other circumstances, too.

**Comment by bbarney7** [comment]
one of your previous bugs was that we were allowed to join a finished game. Now you have a bug that says we should be allowed to join a finished game but the way we are doing it is incorrect. Pick one of the bugs - either we shouldn't be able to join a finished game at all or we should be allowed but we need to restyle it. They can't both be bugs.

**Comment by panzertime** [comment]
Let the TAs decide.

**Comment by thyer** [comment]
@bbarney7 is right - either the stylistic thing is a bug or rejoining is a bug. @panzertime has put the burden on Team 13 by declaring both an incorrect behavior, but both cannot simultaneously be erroneous. Testers, can you justify one or the other based on official Catan rules or the project specifications? The view thing obviously seems buggy, but if that's because they aren't allowed to rejoin, you need to close this and put your forces behind the other. 

On the other hand, kudos to you guys for finding a perceived bug and then pursuing the path behind that bug to find out what kinds of additional ramifications it implies.

**Comment by mcrowder65** [comment]
@thyer if we just not allow them to rejoin a finished game would that be fine?

**Comment by thyer** [comment]
Turning this over to Bentz
