### ISSUE TITLE
Development Cards Button Never Disabled

### ISSUE THREAD

**Issue by panzertime** [thyer/CS340winter2016#365]
This button is supposed to be disabled when not the players' turn, but in fact can always be clicked and always brings up the window.  I have not yet determined if this allows the player to play a Dev Card when not his turn, but if it does this should be upgraded to a P3 or possibly higher.

**Comment by bbarney7** [comment]
This is how it's done in their demo client.....

**Comment by mcrowder65** [comment]
Marked invalid because this is the way the client behaves.

**Comment by panzertime** [comment]
Dr. Snell said like 50 times in class that the demo client is not actually the standard.  Besides, the behavior I was seeking was what was mentioned in the functional spec.

**Comment by thyer** [comment]
I'm going to put responsibility on the testers to either show that (1) a dev card can be played when it's not the user turn, (2) the official Catan rules don't allow players to see their dev cards during their turn, or (3) the specification we provide says the button needs to be disabled. Otherwise, this is invalid.
