### ISSUE TITLE
Allowed two players to have the same color

### ISSUE THREAD

**Issue by joshuahaertel** [thyer/CS340winter2016#367]
Steps to reproduce:
1. Create a player in one client
2. Create a player in another
3. Have the second player create a game and join it with a color
4. Have the first join the game with the same color.
5. They both have the same color.

Screenshot:
![screen shot 2016-03-02 at 10 22 54 pm](https://cloud.githubusercontent.com/assets/16691565/13485488/9068f6e6-e0c5-11e5-883c-46f1355a9930.png)

**Comment by joshuahaertel** [comment]
Leads to confusing game play, though it does appear to be correct

Screenshot
![screen shot 2016-03-02 at 10 26 18 pm](https://cloud.githubusercontent.com/assets/16691565/13485516/d95e98c4-e0c5-11e5-9e5b-d417182cd1b4.png)

**Comment by mcrowder65** [comment]
I actually talked to a TA about this same issue. The issue is that our poller polls every second.  And we could have it poll every .05 seconds but that would be innefficient. He said there are other ways we could prevent this but it's beyond the scope of this class.

**Comment by bbarney7** [comment]
yeah their demo does it as well...

**Comment by mcrowder65** [comment]
Marked invalid because of speaking with TA's previously, will confirm with them later.

**Comment by joshuahaertel** [comment]
In the case you have two clients up and their selecting colors and your fast enough then yes it can possibly be a poller problem. However, this is not always the case:
Have 1 player create a game and then rejoin it, he should have all colors open to him.
Have another player join the game, red will be disabled. Have him select a color, like yellow, but don't hit join game.
Have the original player select the same color and then hit join game.
The second player is still unable to select red, but may freely choose yellow, which results in this confusing behavior

**Comment by mcrowder65** [comment]
Yes - but it's still the same issue of selecting the same color somebody just picked.  If you waited a couple more seconds would it still let you choose that color? Or even cancelled then chose again?

**Comment by joshuahaertel** [comment]
I waited a couple minutes just to double check. Cancelling it doesn't fix it. It appears some sort of additional server request needs to be made to refresh the color selection, ie the first player adds an AI. Possibly the creation of a new game should kick him out of the color selection mode, but that too is buggy as the expected behavior is that the colors should just be updated. What would happen if the server had multiple people playing a game? I could never choose my color.

**Comment by mcrowder65** [comment]
I just tested it too - your bug is right. Sorry to be so pushy

**Comment by joshuahaertel** [comment]
No worries, I understand. Killer code by the way. Notice that most our bugs are superficial.

**Comment by mcrowder65** [comment]
However, it actually behaves the same as their client - so hopefully they don't care!

**Comment by joshuahaertel** [comment]
Hopefully man. Good luck with the rest of the project!

**Comment by thyer** [comment]
I'm wondering about this bug...it's a genuinely hard one to classify. Can someone tell me how quickly you have to click in order for the colors to get messed up like this? Does it have to be less than 1000 ms?

**Comment by joshuahaertel** [comment]
You don't have to beat the poller, you can stay there for a while in order to repeat.

**Comment by thyer** [comment]
It seems as though three bugs have diverged from this issue:

1. Two players can join as the same color as long as the other selection isn't known before they hit the join game view. Valid bug. 
2. Two players can join as the same color if somebody else beats the poller and they don't check before sending the request: fixable by querying the game info from the server before sending the request. Extension of the first bug, but also valid problem. 
3. Color selection doesn't update when somebody else beats you to the punch while you're waiting to choose your color: it sounds like you're asking for them to be polling the server during color selection. It's not necessary to update that color selection - as long as they can't join with an invalid color (maybe an error message pops up and updates everything), they've met the specifications. If 1 and 2 are fixed, then the 3rd is handled by default. 

Since all three of these are supersets of the 1st bug, I'm going to determine that these are all valid issues under the umbrella of the first. Valid P3 bug.
