### ISSUE TITLE
In Maritime Trade, two of the options to get were blacked out randomly

### ISSUE THREAD

**Issue by Saladin926** [thyer/CS340winter2016#394]
by blacked out I mean grayed out.

**Comment by Saladin926** [comment]
![img_20160302_175029](https://cloud.githubusercontent.com/assets/16570937/13486845/c7c8effe-e0d1-11e5-950e-7a1fdda01f11.jpg)

**Comment by kking937** [comment]
By this picture, it is unclear if the bank is out of resources.  Resources will be disabled if the bank does not have any more of a certain resource because you cannot trade with the bank if they do not have that resource.  This is correct functionality.  Can you verify that the bank is not out of resources?

**Comment by KasiKarra** [comment]
To reproduce this without getting a robber 7 is extremely difficult and infuriating.  It will be easier for you to stick a "if roll == 7 return 6" in the code then for me to try and juggle 20 resources.
Which fyi your bank did allow me to end up with 20 woods all together (recieved the last two by the same player maritime trading 4 bricks - 1 wood and 4 sheep - 1 wood on the same turn), but since it is past the deadline it can't be logged against you.
![settlers](https://cloud.githubusercontent.com/assets/16614325/13537913/b388b16c-e204-11e5-9b3f-3bdeabd5a63e.png)

**Comment by thyer** [comment]
I'm still unclear as to whether this original bug was still a thing -- can someone on the testing team clarify?

**Comment by thyer** [comment]
Original bug doesn't appear to be valid.
