### ISSUE TITLE
maritime trade "Trade!" button doesn't change description depending on state 

### ISSUE THREAD

**Issue by Saladin926** [thyer/CS340winter2016#395]
this functionality was described in the implementation notes

**Comment by kking937** [comment]
This doesn't make any sense, I looked in the implementation notes, and this is all that shows up when I search for "maritime": " Maritime trade—I used a PortList to track the player’s available ports, so that I
always knew what amount to send (initialized at 4 for everything, then decreased if a
player build on a port). I then just had a “give” and “get” variable to track which two
resources I wanted to exchange."  The maritime trading functions the exact same as the demo client.

**Comment by thyer** [comment]
Closing as invalid
