### ISSUE TITLE
Improper Display When Player Joins Game

### ISSUE THREAD

**Issue by joshuahaertel** [thyer/CS340winter2016#592]
I joined the original game on a clean server as Mark with the color Green. Nothing is displayed in his resources or points bar. I'm pretty sure this is a Phase 2 error as this happens with the demo-client so I just included this to let you know - perhaps indicative of some other errors.

**Comment by zlohner** [comment]
Please use our client to test our server, not the demo client or your client. The demo client won't work due to an cookie difference between the TA client and the specifications. Please note that because our client doesn't have an implementation for moving the robber, playing the soldier card, and playing the road builder card, these options are disabled. You can test these through Swagger.

You can run it by entering the command "java -jar catan-client.jar <hostname> <port>".

**Comment by joshuahaertel** [comment]
Sorry, I meant to say that this happens when I use the demo-SERVER in addition to your server, which is why I think it is a phase 2 error. Let me know when you want me to close this issue.

**Comment by zlohner** [comment]
Do you mean as soon as the game is joined? Or after the game has started? If it is before the game has started I don't really think it's an issue. If it's after, that's a more serious problem, but this hasn't happened for us at all.

**Comment by joshuahaertel** [comment]
I enter the default game, so it has already been joined and started.
![screen shot 2016-03-28 at 1 49 55 pm](https://cloud.githubusercontent.com/assets/16691565/14088309/0060096e-f4ec-11e5-9efe-9095b45b0653.png)

I get a similar screen if I log in as Brooke or Pete before Sam rolls the dice. I think the error is general enough so that if a player joins a game when it was not his turn, he cannot play.
