### ISSUE TITLE
Cannot Create New Game

### ISSUE THREAD

**Issue by panzertime** [thyer/CS340winter2016#606]
If I use a client to create a game, I run into issues:
- our client says that it got a 400 from the server, but the server prints out a ton of stack traces
- the demo-client is unable to create a game, also; it prints out NullPointerExceptions from an unknown source and your server prints no errors; exiting and logging in again shows that the server never created a game
- creating a game in Swagger works fine, but you can create multiple games with the same name (not sure if this is a bug, if I decide it is I'll file it separately)

**Comment by panzertime** [comment]
Note: this happened when using a newly-created user, rather than a built-in guy

**Comment by zlohner** [comment]
Please use our client to test our server, not the demo client or your client. The demo client won't work due to an cookie difference between the TA client and the specifications. Please note that because our client doesn't have an implementation for moving the robber, playing the soldier card, and playing the road builder card, these options are disabled. You can test these through Swagger.

You can run it by entering the command "java -jar catan-client.jar <hostname> <port>".
