### ISSUE TITLE
Cannot (Add AI In Order To) Join Created Game

### ISSUE THREAD

**Issue by panzertime** [thyer/CS340winter2016#608]
I used Swagger to create a game, then launched the demo-client and tried to join the game.  When I got to the "add computer players" step, I was unable to proceed; clicking the "add player" button caused the server to spit out a bunch of exceptions and stack traces.  

At this point communication between client and server appears to cease; the demo-client begins to complain that the poller is not getting a response.

**Comment by panzertime** [comment]
Adding an AI was not possible with Swagger, either, and didn't send back a 400.  I would think if you just didn't implement AI, you should at least send back a 400 and a proper error message so it can get handled by clients.

**Comment by zlohner** [comment]
Please use our client to test our server, not the demo client or your client. The demo client won't work due to an cookie difference between the TA client and the specifications. Please note that because our client doesn't have an implementation for moving the robber, playing the soldier card, and playing the road builder card, these options are disabled. You can test these through Swagger.

You can run our client by entering the command "java -jar catan-client.jar <hostname> <port>"

**Comment by zlohner** [comment]
Also, adding AI is disabled as we have not yet implemented any AI. Please test with multiple clients (on one machine or multiple, both should work)
