### ISSUE TITLE
Unable to purchase DevCard when I had resources

### ISSUE THREAD

**Issue by tcashcroft** [thyer/CS340winter2016#93]
I was unable to purchase a development card despite my resources saying it was possible. 
![devcardborked](https://cloud.githubusercontent.com/assets/17575428/13451701/a438371c-dffe-11e5-9d8c-7edda74293c9.png)

**Comment by thelaurence** [comment]
Unable to reproduce. A full screenshot would have been helpful here.

![image](https://cloud.githubusercontent.com/assets/10649804/13567569/3845094e-e419-11e5-96c2-a061722b5353.png)

Notice that in the above image the dev card purchase is disabled because it's not the local player's turn, but it's hard to tell because our game status button wasn't updating correctly. If you look in the turn tracker, however, you can see that it's actually the green player's turn, even thought the "Finish Turn" button is still enabled.
